apiVersion: apps/v1
kind: Deployment
metadata:
  name: dash-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dash-app
  template:
    metadata:
      labels:
        app: dash-app
    spec:
      containers:
      - name: dash-app
        image: your-dockerhub-username/dash-app:latest
        ports:
        - containerPort: 8050