apiVersion: karpenter.k8s.aws/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3.medium", "t3.large"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["us-west-2a", "us-west-2b"]
  provider:
    subnetSelector:
      karpenter.sh/discovery: "eks-cluster-subnet-1"
    securityGroupSelector:
      karpenter.sh/discovery: "eks-production-sg"
  limits:
    resources:
      cpu: "10"
      memory: "32Gi"
  ttlSecondsAfterEmpty: 30